# Deliverable 2

In [2]:
import pandas as pd

In [4]:
# Read in the vine_table.csv file as a DataFrame, and perform your analysis using the steps above.
vine_data = r"C:\Users\mhern\Desktop\Analysis_Projects_2021\Module_16/vine_table.csv"
vine_df = pd.read_csv(vine_data)
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,REAKC26P07MDN,5.0,0.0,0.0,N,Y
1,R3NU7OMZ4HQIEG,2.0,0.0,1.0,N,Y
2,R14QJW3XF8QO1P,5.0,0.0,0.0,N,Y
3,R2HB7AX0394ZGY,5.0,0.0,0.0,N,Y
4,RGKMPDQGSAHR3,5.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N
2643615,R13RP6H1OP0BFS,5.0,3.0,3.0,N,N
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N
2643617,R30D2N6TX0OFS,3.0,7.0,7.0,N,Y
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y

In [5]:
#1.Filter the data and create a new DataFrame or table to retrieve all the rows where the total_votes count is equal to or greater than 20 to pick reviews that are more likely to be helpful and to avoid having division by zero errors later on.

total_votes_20 = vine_df[(vine_df["total_votes"]>=20)]
total_votes_20

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y
...,...,...,...,...,...,...
2643586,RDDVO19Y8YH01,1.0,12.0,56.0,N,N
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y

In [7]:
#2.Filter the new DataFrame or table created in Step 1 and create a new DataFrame or table to retrieve all the rows where the number of helpful_votes divided by total_votes is equal to or greater than 50%.
total_votes_20["helpful_votes_percent"] = total_votes_20["helpful_votes"]/total_votes_20["total_votes"]
total_votes_20

C:\Users\mhern\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,help_votes_percent,helpful_votes_percent
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y,0.870968,0.870968
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y,1.000000,1.000000
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y,0.935484,0.935484
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y,0.833333,0.833333
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y,0.964286,0.964286
...,...,...,...,...,...,...,...,...
2643586,RDDVO19Y8YH01,1.0,12.0,56.0,N,N,0.214286,0.214286
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N,0.983051,0.983051
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N,0.941176,0.941176
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N,0.857143,0.857143
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y,0.850000,0.850000

In [8]:
vine_program = total_votes_20[(total_votes_20)["helpful_votes_percent"]>=0.5]
vine_program

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,help_votes_percent,helpful_votes_percent
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y,0.870968,0.870968
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y,1.000000,1.000000
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y,0.935484,0.935484
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y,0.833333,0.833333
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y,0.964286,0.964286
...,...,...,...,...,...,...,...,...
2643577,R37NBT4U1EL04K,5.0,47.0,61.0,N,N,0.770492,0.770492
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N,0.983051,0.983051
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N,0.941176,0.941176
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N,0.857143,0.857143
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y,0.850000,0.850000

In [11]:
#3.Filter the DataFrame or table created in Step 2, and create a new DataFrame or table that retrieves all the rows where a review was written as part of the Vine program (paid), vine == 'Y'.
vine_program_paid = vine_program[(vine_program["vine"]== 'Y')]
vine_program_paid["review_id"].count()

170

In [12]:
#4.Repeat Step 3, but this time retrieve all the rows where the review was not part of the Vine program (unpaid), vine == 'N'.
vine_program_unpaid = vine_program[(vine_program["vine"]== 'N')]
vine_program_unpaid["review_id"].count()

37840

In [14]:
#5.Determine the total number of reviews, the number of 5-star reviews, and the percentage of 5-star reviews for the two types of review (paid vs unpaid).
#numer of reviews 
vine_program["review_id"].count()

38010

In [19]:
#the number of 5-star reviews paid 
vine_five_paid = vine_program_paid[vine_program_paid["star_rating"] == 5]
vine_five_paid["review_id"].count()

65

In [20]:
#the number of 5-star reviews unpaid
vine_five_unpaid = vine_program_unpaid[vine_program_unpaid["star_rating"] == 5]
vine_five_unpaid["review_id"].count()

20612

In [22]:
#the number of 5-star reviews paid percent
vine_five_paid_percent = (vine_five_paid["review_id"].count()/vine_program_paid["review_id"].count())*100
vine_five_paid_percent

38.23529411764706

In [23]:
#the number of 5-star reviews paid percent
vine_five_unpaid_percent = (vine_five_unpaid["review_id"].count()/vine_program_unpaid["review_id"].count())*100
vine_five_unpaid_percent

54.471458773784356